---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: hedgedoc-postgres-daily
spec:
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: hedgedoc-postgres
