apiVersion: v1
kind: Secret
metadata:
  name: hedgedoc-postgres-b2
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:OA0eyuP3nqatyz0K6bnHJD/MhSuPMkr48g==,iv:R6OvrfsUoJGF56b0OxLrftQaXwgKnCi4XmiQ9OPL70A=,tag:+ZM4GLbfHlHGEO7W9iTq0Q==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:30mgQsQV3kjL5atVgspAg/aBBCiDOsks8FnZqO43Zg==,iv:3IjdL9sVhkVc/gSiJzZnLc2tE9+GeQKLPNNAWi8On3A=,tag:qFaeO1a7HnRdHiPJDo2+qw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YlVkVHJOdmRSLy9uVkpE
        MDUzK1pjYy9HQXJZWHJhdExmWTNLeWdHVEI0ClQvWTlNWDVLQlllVExjL2c3T1Zm
        a0JQemNudnV4VnFLY3A4SFNhemsrTWMKLS0tIFk4b25oVi9Va3ZSYjhuMlRUNHg2
        aUhkR0UwUSt1RjRJa2JubmZSYlZxT00KvILSHXUdi2or8S7/cQhFfbPbH4aEWHre
        bJfpBgfgYGpOGYNVR2IKBRae6x45smkCRS6lhiTIJoG2r1Q1LsTInw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T20:12:28Z"
  mac: ENC[AES256_GCM,data:OB72hh42BNbMZDLRUcHZHExkcFYIYJpA39yUbUIEEmRdHCQIw6wRBKUWiPnEUvptiQ03Wra+VTizk34LRdhJOxE6utbV5sdNAmkta1fcKYt/FpMzzK6xJkMsXlwd9GGqLx4029fOMwUaVLCePrdmg7wrPeHkZDl94RIX7FxjAyo=,iv:cbS8d5TcXUNSDrcUO9BXgH43TYdbex8t9sPGldnc9ms=,tag:OEZq3t/Yeg1XyEE+RdCmBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
