apiVersion: v1
kind: Secret
metadata:
  name: hedgedoc-postgres-user
stringData:
  username: ENC[AES256_GCM,data:zTzhICVz5RE=,iv:4T1Zj/06AykfPxDWhXJPSmYn5748Yb38/2f0dSo5iJ0=,tag:BPmxPpFWB0zzREUQgLtkEw==,type:str]
  password: ENC[AES256_GCM,data:gU/rC8s6nGbgn0VKwp0sgJh3GOnKsLGomSQI7pSJQGLy2kWhrKD5dg==,iv:0atTZiTDAE9vv0Gody0dVQjN4niKkUeLl4+5RVm5uAw=,tag:l0p2SYnAMegETPT/S3w5Qg==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeTllOE1WUGdIWFk1OStV
        M0ljQ1BaUmpYOGlXY0JUT2NiQUFiQXdrSlEwCithYVJ2eWVuaHRmV1JRcVJxcHFs
        UTRLeXZFSGpLaFhWeW9HcUowaU1jUlUKLS0tICtCL2VYQUFyR1dHaUNkdnNxMWxv
        UVdYeUFicm1HazEvMUViNFdhMUZIOHMKeOO3SpIfiB1I6GzI5ApHkxJLHxIFk8+0
        byHNAQ94mOA0EkOmsAsqgFcVC/ZYtI4Tv8s6thT4nFpMrm987jKj0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T20:12:27Z"
  mac: ENC[AES256_GCM,data:FTq3sEJYOFLS2ZRT6/arGTRQGHPFhSkPRG+T6wjfvtgrTMEx0NaC2DTizwF6mK6XT2ks7tnAG5IQmlboDMs5WFDzlA2yuHUqDZmazBb0DAKxe8ueBxqZJIHXDMPPFMtkj5nh+MVW+ikASiFc0h22YVc3O8z1fXLj9/ohyj+1rFA=,iv:WfQ41lBh85OGBLHbrU4YbgpgpF793HhqNuOzIorNMRE=,tag:3B6bzgG2xUKT82W9hGyVQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
