---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  chartRef:
    kind: OCIRepository
    name: trivy-operator
  interval: 1h
  values:
    operator:
      replicas: 1
      scanJobsConcurrentLimit: 3
      scanJobsRetryDelay: 30s
      vulnerabilityScannerEnabled: true
      configAuditScannerEnabled: true
      rbacAssessmentScannerEnabled: true
      exposedSecretScannerEnabled: true
      scanJobTimeout: 10m
    trivy:
      mode: Standalone
      severity: CRITICAL,HIGH,MEDIUM
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
    serviceMonitor:
      enabled: false
