---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./networkpolicies.yaml
  - ./authentik-postgres/ks.yaml
  - ./authentik/ks.yaml
