---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.4.1
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 1h
  values:
    global:
      env:
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          value: "${AUTHENTIK_BOOTSTRAP_PASSWORD}"
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          value: "${AUTHENTIK_BOOTSTRAP_TOKEN}"

    authentik:
      secret_key: "${AUTHENTIK_SECRET_KEY}"
      postgresql:
        host: authentik-postgres-rw
        port: 5432
        name: authentik
        user: authentik
        password: "${AUTHENTIK_POSTGRES_PASSWORD}"

    server:
      replicas: 1
      resources:
        requests:
          cpu: 100m
        limits:
          memory: 1Gi

    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
        limits:
          memory: 512Mi

    postgresql:
      enabled: false

    redis:
      enabled: true
      image:
        tag: latest
      master:
        persistence:
          enabled: true
          storageClass: longhorn
          size: 1Gi
        resources:
          requests:
            cpu: 25m
          limits:
            memory: 128Mi
