apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:YYphKOC+Y82SioeQur+l,iv:9fcPISYiDpFYyPcaQetpMNEoND6VZT361UJt9cMn9us=,tag:3Tv276zbztgIRpWl7g1lCg==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ezVTTf/box4rDXrj2ecmlHunKXMWrdEoo5VLGABMprkgsohTiaAHpVxeFIJoQGbpAMtuoA+hwpKquSGD60MB9w==,iv:dMKxDzfGbhaeR/GpuiAU/5yQN8LRRzf5yxWrcstm8GA=,tag:dUS7J6SNGwO5f3dM4x7OCg==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:if84q8ZrvFOfYCQdBCnVzzaNU8SbP8WZwlK2qvvIdxKGA0IF2DrvB4aSomhMKTMp6XomcwZgEqM8MY/KPSUoIg==,iv:07v1BGaj6brSJxJsXMXB6XqbECP7X7L8HLYdoHNRuwg=,tag:tJMm4o1ewauXB2V33FN8lw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:P0b4pRDVgC/vViuyVRYknoMEtgPoy9CZGC3KJe0wmYnvrhxgmrItuVU3pnDRDuZrPtO6yxow5bmnjb2upYbK7g==,iv:Bb4vsjB3BlGuLzcUXcmwL3ih/G2rGTwmCmTaYFFpqmc=,tag:iShIS9bVaSvyUlp453aQkA==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:lm6b6DfUS81IzSBmu+xXNDYucN/6gybVxgaogp4HMv+iKzN2G6aTVG3NDyrj073nKvzFXnBATHCgZ1J0zSlmDg==,iv:RIJzn2sm2g8Mo/iLzwm3OhUA5IHwqs5ygBlute9KYIg=,tag:ymT++Xv9C2guVzlJZN9H/w==,type:str]
  FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:AUX26aSUKgP0WMcAW0RKw5ukuSuVD45S0zl2rpNg0eEh8jSeLHH9M/ZNDNNH5be188VB2l3DC4GZ7aRR9F4mnA==,iv:4xchLBOgKWPXJtxZya+9Ez5uIWgZevblr79+6nu9NpQ=,tag:5XlH9YsJicuZVSsUnSZ1vg==,type:str]
  FORGEJO_POSTGRES_PASSWORD: ENC[AES256_GCM,data:debuxg0gJBg3iQUSQrcjt1maIvsEruP9hHD/SGfUIemQw9txmxqrYPbseFWWODIjZciU31NaO+x0dx0rzMnRpw==,iv:N3OiEo6lOSygM/voFYNQe37YXFYRw7GmDWp6yOAeNGQ=,tag:SarQAUxqauL74abpZTl82g==,type:str]
  FORGEJO_RUNNER_TOKEN: ENC[AES256_GCM,data:k9PHsIGReDcWMnAaLUYZtDu8FmhFYfTVsZZD8qHDRqSaQJUsr4HERQLR7A==,iv:Mt35ObBeeFwyJecjxHkvE9KTUz3Yx77okd3HvljHofI=,tag:BQxdVA/qw9FS3vlKdVG3vQ==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZjdmNUtJckJTaElVcktR
        S0VVazBCUjZiWVovSUVuSStJMjloZ240UUZjCjBlUG9mRjRaMVArdGdSUkVsRE9Q
        MVRQK0xrYUpGRTd3YUNyWk5ZRVFPZ3cKLS0tIDV4Vit5SDQ0eloveGk2b3hYVmpn
        cHJlR0ZwYmtKdmtFNjhuZnVxR1lUU3MKLq7CNC8dZTf5Zw4OinNrUp6DcA5noVAB
        lGj69hb2uo794EQwvcdGfgXbxuoh44YEVfcLUdcV4/ZhLM009BIzzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T00:56:22Z"
  mac: ENC[AES256_GCM,data:eaNfzh1VisBcS4nd06kb49WNt0MZ0E/GMc/2tDCDusPloEkOnDy1s0HpXNtiqfdtEcYmf1khf6ZlgxE8b3yWcN3ygXWbRDHYfGfR0wm9L7eV90SVB/J9XSBi1d5xGFu9QN/dt//nmD8Rzf4BOslCOymMNOfeQJFINS1xJeeOM2g=,iv:NAGmsQirCn6gNbVjpuS2oFTE2ske7r9HMoCXsdSudEQ=,tag:7N/+8UB6rqIw+4okQVyP6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
