apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:55fXeCYIRKKZsHEEEzRN,iv:u7OE1fDu8gdJwijp5zxKTLdh8z0dn9NDBd6sHFA4Vtg=,tag:bnZaQlHrCof2BW7g2tG8Ww==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:osq6dxlyYfKS42g87dSNEgfzB0cEpCfCtMZY9AvYLOS23DQ0tTohOL6/tDUS5ROPH4wtutzJ5tLN73f8MR1tzw==,iv:o92K8UF6m9fGh+MJFdzE0Kzc4J0rI/5MSAr/d2vBvoU=,tag:i6jxH+pm5mwA/a+hpIrYrw==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:BOhb6iMRaLkdJAjeuj4I+3Quo16v0bPqpDM1AXeRcJzVZLHmAj+S8gImWkdKo7niYzBPTK9kAqCQcXGj+UzBtw==,iv:zG+OrZ8/2VZd9yo08C2mKuB7rP1Znu66gRTizVTgOdY=,tag:6rFGTuFxC4UCqoGowYo/pA==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ttyrvALS8lstbSLlYvNAKZpj35/nXUZ2+E7sgjoh6THLQJhcZYBKGoKICYsKDv+FLwUPKH2eK48aZ2odY1vmhQ==,iv:GLdLFSvBWDcFtQt3uBq10AuT0/KiB52m3biV7HZytV8=,tag:I7btS8fivf53F50jCJ4vmQ==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:cYxvEPdedla0UvW7t+MinMdMzcnr5LmcCFRyDdin++IlLaFTWukiT0ZhdEEet+2+zNJJdF4jjG1APhDd5osjZw==,iv:fJTcP39m49YajUbN3PT7GQQIwE0I2KulKE/mLHmBZT0=,tag:pEcReovkhD/2GS6j4YBU4w==,type:str]
  FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:DqCehgeA00obP22pJmHtgiZcsOIFzqb3BoE4yNZu0wKSXiwcyDCCy0q3fjcceoOjw/5ciI9wQaYtDY+HCJ+LwQ==,iv:/RkWd9Bs10yhas/sSjPnYWuSlQ5iHhpvnvgADQ7+LMs=,tag:vzAgB2IR3rkqVC/bXq+o1g==,type:str]
  FORGEJO_POSTGRES_PASSWORD: ENC[AES256_GCM,data:veF0b+VtowFJs+KPaSGL3XW5cKwa9mX8p3dC+uefiVOqEnSxTvG1LgYM5ggOnIibyyninh2HjlMKB7Jhw8BCTw==,iv:LgUuqigo5jBmZkRQQJPiQTS+kY4QeLqIssNMmeq5MW4=,tag:Y8bLGDouhU5sfIch5oNzbA==,type:str]
  FORGEJO_RUNNER_TOKEN: ENC[AES256_GCM,data:9hQnyjfmmgQAESoe4SWjndoiz7YjE9HCzUTWZdESZouTXGswr63ONsJitw==,iv:gm2r0+8zxB30+Kwgp8PYksG9/deBtYKm7D0cjM52XCM=,tag:7HqAp7G7C90+FobMOHrOmQ==,type:str]
  HEDGEDOC_POSTGRES_PASSWORD: ENC[AES256_GCM,data:2LLE+XnhQl7EsVOl536y6oqC2RYCcgeY2pwwQ2IdwhewzpEfNiatbw==,iv:pB9F5QMby/IkA9yoTdkW6t5S0n7ni67IgDknJingbBQ=,tag:8owFw3YpRklXetb9Kel+eQ==,type:str]
  HEDGEDOC_SESSION_SECRET: ENC[AES256_GCM,data:u0QqHzyffFDjithqkKOLVihCxzy2gqO1LqPNPEgQnLXOS7KSJmtENw==,iv:54nXB8vAL1EdX4WY4NYt55HQAV28vzseTNeET/8TnjI=,tag:NjGW/EtUuGHio6kzRAtagQ==,type:str]
  HEDGEDOC_OIDC_CLIENT_ID: ENC[AES256_GCM,data:+8bVEzF2h18yHKAa6dOn9/m8hXsqvehtSJv/wVehStyZSJkfKxBRMg==,iv:1gGlBPrWvBdoWe32jpHlgh7g4ud/BU+F3Cdj81x7O0Y=,tag:Jg26U5jfQNQfa6xHIuFlpg==,type:str]
  HEDGEDOC_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:FtcgDUo0C+KI2jqwULxcMcu1xzALFsblEyESHlnwUinose24KL/1ltz3YCyLC9wGkhQG7wFsNxnsEO+rhFZwFY4q6XxPhPLalk5nTtwztGXv1rgjzEpUPaPFw+dzmZm9B9dqESV+HHfLdzgaUpKMsWGjQAgrtdmHAS5wDgBQlQk=,iv:khIW2DfReSV0qn2LvRnPvhTTFuUJIkR1iB1hGkGZ4No=,tag:A6IMPVi7JAeRYCXJHLkEjA==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubXZJOS9ENExqakdlWVFU
        UXJLQkd1cW1hTXBwMDN1NkU5ZjRXSTFUb3hJCmY3emRnRjVmMjd2b25ldmZFSjdL
        QTJhemF1ZkVOSzdmZTFxRUVheEJPRVEKLS0tIDluZEFnZmFEbTZPdFFmUEtRcmE5
        NUM2WStXN0ZIZENMSlEvbXlEYkhZWEUKGoR6fADiimNEKWLcjPyOO40aWLhoebkd
        FSMMgrhdKQa/ef3wHERu4ojAL3p0jLiYCq1aBAe+I+h3H952uFU5mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T20:44:34Z"
  mac: ENC[AES256_GCM,data:iBN1Y73ZSy1xVhCrCsWC8AAc7vRj2F8QD4L8S+pHz3MKG3qGK0MByYkB+Jd9fActCFWVu2sXQraVtrSAm2cdcG/pyKvIzXfGScVgRQ2k0LZlpEpd2izh2gp4tpN1XClSpUgvKDx4pcrDl6NzWXcR+vhrfVtY47bthRwng+L949Q=,iv:WyfBzzLHz10prI8bJk/Dn0b1Vmp6Ag+ypmJf0/m2jbA=,tag:zkkcoXyPGIdW9BOo+uUTZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
