apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZpBtWi98kHb/ut/cAwCi,iv:68TIqaW6PRW9pqNqbjPIjvZT9B9GQq4TvdcsUG6ea20=,tag:Z1q3G/0KZA9ijYVlogrvZg==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:5Pz7UBFMn7PfJrk4ebIPkTyxooOykwYosnQvVdHzhinKk5LxKbRLRXxP7ajauA+jnFwcAo0G1BOqqJCZEj4XOA==,iv:UGLd16O7HYx9PF7t8Our73LmcUXDk1xP8Stv+sc19TY=,tag:n+8CnFwcv2YJFgYm3xlJsg==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:+4ci5uh2eIt2cmWndk1Q/24Nhi69Hg9y7YbwOqiKa7ZdUz7TabJvm5A++A9frvZ4hJjMmMM/LmNBqEu1jIuiyA==,iv:FANKt1LkwYkv8WjD5BMJOit7jhCMZaVl7tT2RF4We+g=,tag:4qqT0gOZ+Z1JIBp1DFffUw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:YAERvxe4OyCkubaMugjHddRNpGS88/T+zsM5DMRpB6XiqTigavjsHs+NLYv3RDwZD0H0KALyNbQJ5Rxp61U7Mg==,iv:I+DDzIAoQ1hZm//+FkarJoFxvuKEedDPIiTwsmci+hw=,tag:4ON+Tp8ANlCcs40uA4E7MA==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:3oS9Dmf4kOhdRpLCbjNWdu0CqGWaKO8p8kLSdYb0/szGfYGA2wjURcR7qbWLspqfEj2QEygWCx6CmBIGSsb5aw==,iv:dpBhq1qBomedlMsrxGPUTuAuLbFzNYqj8tH6ufJVd0Y=,tag:5giayudzEZ9VIOPWNOJprA==,type:str]
  FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:fQeKlOxQwyim61Kta0+VvSuz8/zEA88aikaTK5aEGOrmHT57tA33MCjlcWUQRXJ1S8CSJzHYHFAjOxo2u3uUSQ==,iv:+s6oGh2v18m4CRYDBlha9BjP5n1bLQnKJRiM3gAaho0=,tag:9T3amGWPLzosk4RvL9RRHw==,type:str]
  FORGEJO_POSTGRES_PASSWORD: ENC[AES256_GCM,data:k5ha3Ag6TTrEej2GbQvLc2sla+5CAB7imytN6S6Rl8pE4yZ9B/xmSvwWtEI1gupZ70voUIZIZPIY8/qRFKUy5A==,iv:yv+Txd8FL2RV1mzjTO/sIB48eMWjkZe1NnNhlRNOpkM=,tag:5600DTBTuoQoBnNSbzANiw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidnVjVGlNdzdUVVJNTTRm
        Rm9PN2dnZisrdDJ5TEJHV3NTdGtWUUZ5ZHhJClpsMjEvL1J0cUJtYkFVcHFFQVBQ
        RnlSdmhrVWFKMmREeTNMUEhvcVM2T1UKLS0tICtiMjJRaXNkeFJQVWJOOHNvK2pS
        S2U2N1ZEbTBnMFZ1MUl5aGhXa01LcHcKudsz2rbsoNnE3GH1sE4S3egG+gPTe+oF
        NIZpzyzCsiS5/4qy9PCJ5VvQ8eHQOTpY7RTRvnLmFNDjU/Q5X6OMgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T19:20:56Z"
  mac: ENC[AES256_GCM,data:g9/c9usqus6F5f7i478uZ7mtDAtrROEnUKpK9C+Cnc7I0ZnnJe1UpD5imJP8i8nQWOp1qATGOpD2qc1tGGRoj5PLqww+vCddDtnsEfYO5/Uz1ru9xd+ExvWmCv3nLW0/ciILuYZSJFSra9+iXobuRrLWH/BMz27WBrPjuQOKX6U=,iv:t8oPd1rTGlhm8P7A+SE/wLK2W2Lissg4fY4jV2sOWcI=,tag:DKmd7lGzEXQ2WennpXC7vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
