---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: forgejo-runner
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: forgejo-runner
              spec:
                strategy:
                  type: Recreate
                template:
                  spec:
                    containers:
                      - name: dind
                        volumeMounts:
                          - name: docker-config
                            mountPath: /root/.docker
  values:
    replicaCount: 1

    runner:
      config:
        instance: "https://forgejo.${SECRET_DOMAIN}"
        name: forgejo-runner
        token: "${FORGEJO_RUNNER_TOKEN}"
        file:
          runner:
            capacity: 5
            timeout: 3h
            labels:
              - "ubuntu-latest:docker://catthehacker/ubuntu:act-latest"
              - "docker:docker://forgejo.keatoncable.com/maven-hair-co/ci-docker:bookworm"
              - "self-hosted"
          cache:
            enabled: true
            dir: /data/cache
          container:
            network: ""
            privileged: true
            docker_host: ""
            options: "--volume /var/run/docker.sock:/var/run/docker.sock"
            valid_volumes:
              - "/var/run/docker.sock"

    dind:
      image:
        repository: library/docker
        tag: dind
      resources:
        requests:
          cpu: 22
          memory: 104Gi
        limits:
          cpu: 22
          memory: 104Gi

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi

    nodeSelector:
      node-role.kubernetes.io/ci: ""

    tolerations:
      - key: node-role.kubernetes.io/ci
        operator: Exists
        effect: NoExecute

    volumes:
      - name: runner-cache
        hostPath:
          path: /var/cache/forgejo-runner
          type: DirectoryOrCreate
      - name: docker-config
        secret:
          secretName: docker-credentials
          defaultMode: 0600

    volumeMounts:
      - name: runner-cache
        mountPath: /data/cache
      - name: docker-config
        mountPath: /data/.docker
