apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-token
stringData:
  token: ENC[AES256_GCM,data:2IxuuZyCLwnNs4I69PfxfJXZHIWjQ5t0kv3p910680Ul2++p/hdN2GXHjQ==,iv:QDvdcNGPN6x7ksEE1gCjEjBipzHB0ZVVKlq/LvXBAdM=,tag:+X4SL0a2w85oJ+M9Bp0W3w==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMlBJdDh5SCtEaWZzSXNy
        QnBTYlFySWhObkZrbFhtSFZsUmlyalM2STJjCllKbzhqQmVpcjQ1K3BwTDB6U1Rq
        MTNGOEVkbytKeXJYMUM1MlRwQ1grK2sKLS0tIDhTNFBKYXRQYlc5Ukd4b2xMTmdC
        a1RmWFBxeE9EcDhUeGJ1dnkvUWdJSTQKahUAgFHKkK1mTnTnpUWi2sepvpEZD3hn
        mHZMPy/umTdfFIAMTjuBxx0mSVcSsT/GRJh0xcy1yiUeZEMN+XnSmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:21:34Z"
  mac: ENC[AES256_GCM,data:dgd7+3gQA6Y4xsNAzOqo227NQ1KDsmOx1UBXOEnXvfZf7M+K9A85vQKWHexvivxSpm6MWk6gVG5m5Iqj8FOubRSEiVZwzBougxkUsxKX7c6yMuJAJbpX5WmJPnGsxZsZE+D/AnaWLVWMJWpz1jCQst/vrVP2a9Ezc8cHHmdiEzI=,iv:5RCqP8NUz5TpqJRL8Df+zOaNrK0L2o1a1NOUzP66woU=,tag:HClc9sCFZdMVz5QtHu9IxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
