apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
stringData:
  config.json: ENC[AES256_GCM,data:C1JoOpeOJUjN/2O7YkpMM6hekVO6PCCtw0GZEUNOUPs56RpJ9+sdlr0C+m+fpQpkVCx0piYzFFne6p7quCgdEqcWLmUpqi7GxNpYwuW9IjguiY4vOdIpjKXqUwUNXy9Itk1ztH4hyNiIY9m86ObzQMnKG6ox5rTD4cxw3VMdU/KlKZGy7msJGUAmdBNMtroJWA==,iv:ZFh+eljR8efP6UaZd3rU9MZ77ygqsE92CsugmW7kYlQ=,tag:WIFJ4N0Zg6sMGtHlI2WWkw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QnN1ZjZMUHdoa3Jyc203
        aTRsQk1CZUJRaitzWGhFWjYxT3pucU9ZL0ZJCjQ3bjdQTzkzODBSaExQT1NhaXRQ
        SGRkN0tibjVTajZrN0ZnVExGTzRicEEKLS0tIGxIRnNic1BZMXBEeVBJeTc2dml3
        ZDRwWlJKc0laSGtyd3pvNEcxMEQzb28K2+SoHg3F3THRkNWh3tNQt3b4s50cfF5J
        NpxSnSoaqqnPb8ldeJPo/7jtVpVLhFSi/5HteIO6AorS48nz05XUIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T13:49:09Z"
  mac: ENC[AES256_GCM,data:c14UAN9BtrAqcGqAzuRV3sdsPn7N10/zEspgL/FG0NC3oOTiOkYxJILtPhoU8XuVj6e9D8fp7GwpDmGX/rUPk5LLpwjjwR/L2Lq33Dxigl3YUnXtFuULFfxVCidIgDo/GFFSSxWmnlEcJmzaLUpJdVG4GEjBCywnXWnl5ocNLsQ=,iv:OY+PkyNRn8+q77ZYH7luO5wdjxC5lXnZKRRxADwS3/I=,tag:GfvXzYtDdGshD/+ntBhyXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
