apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-token
stringData:
  CONFIG_TOKEN: ENC[AES256_GCM,data:23OkU/9UhZ1uzZbjRcZ7pWgREBndhNFS1g5EOVUme9nV3PduRJsPLqyxUg==,iv:qONHaNRiHF7CBEdAbdno/N88Qty6L6Vknqt0ds8RPjk=,tag:o1JhoxIwLbrZBTBjxzcaQA==,type:str]
  CONFIG_INSTANCE: ENC[AES256_GCM,data:KbaeFT/9vtYUjx4fJs5vprkwwazF1PuAadOTXnvhijU=,iv:Kf5im+f8chbjxTPv9JatIRWhSoF9+CCKE/XEQknGdPg=,tag:C5U/17+Fk3VJ+psbLKxGDw==,type:str]
  CONFIG_NAME: ENC[AES256_GCM,data:kNogDMNMW12LgdDdqec=,iv:rtn6HLRAFKokNwFUk5ofcHe5q5DXIbmN4oGeynmbGqM=,tag:KZfbBzFkMz1VSic3kVRSGw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK1pzbFZ3cUhjU0RCdTV6
        dFlieWhqTTZTU1NOMGJuWGlJY1ZSZ0xpanlzCmhyY3gyenhtdlRtekZ1bVZWZ2NT
        a1hjWVlhZVkyOGhtM2N6REo5eCt2VWcKLS0tIGU0SWtEcGhzRFNJUEhoQVRuZWlY
        Y3BzS20wYnlJdndVQndRN1d3RW9nejQK9nFE7tt9AmLZrzSQL4IoCi2lQIMHizWB
        JwkVrGlHu7SBXewiwkAigAwSk6NhdwXlyOmBrOVC5P02TX/GIjvgQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T23:14:38Z"
  mac: ENC[AES256_GCM,data:3XchmwvU4dgy5FgYmhVicylnjJ9o/y+XSisq30Cmp36xCmfgF2uXitE7rO8csXumCJTHAsDTvpRUmpgV03S3GlsUv04p54RyHBs1dZV3anAbdQoXXCAOCoGE8aDLQ4P37+5dK7+hZ4qWV4v6qMRv0FlCfoGeF3Cp5n80LGPsTYQ=,iv:e6BUYUqqZSdhNRActHakc/Qya11rkdhGYofWLXriApw=,tag:QXusqk3Q4hqPc8hcfTKctw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
