apiVersion: v1
kind: Secret
metadata:
  name: forgejo-postgres-b2
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:b9z2d1u2hj6TBI2hc24JnSpw48bV3aQjzw==,iv:PbPfgV0L+almXIdkR4q+bAvSXo7+XoE+8MPc1ggqNOU=,tag:UtGzS+v7JMQWI4q+cVHB+Q==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DnE3vmfb5NOcuvqjeCUSF6ELiYLguQxh1diawIhF6g==,iv:L7egbflJ+DFpqS0176asnB5Gt91RqYESVB4DCtuGTxg=,tag:f7dxKeQoVNdh9Ef4erGQ9g==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcjF3d28vUzR4a3JtYStP
        ejhxRGpEUG5xUGp1OHkwc2ZidXBsSXFOL1g4CkgzbVEvLzlXZk8wK20xcnh1TE9k
        VjhnREFSTUhpdGlKeTBLa0pzK2N1WEkKLS0tIDhqQm50N1hybWtnTUt2LzBIc1kx
        c0ticHBEQUlXd2p2ZFpDUXE3YjhIMDgK0XrRRN2oqcmAMIToOvb8ccOTLZU21MKB
        zGFDHRtyp2Sd3BozUPZxkkgPssqN/NO93f9CeF6X1GivRtrkNuCRzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T19:39:14Z"
  mac: ENC[AES256_GCM,data:3/ol0J0iZjQuuIsyzcy6kZS3TuRY8yA5WlAfdVelucPPftSkykt15/Z1lKdpluv77Zk1wTvHiiT6Sy4rRI3FzkLtvw2D39ULEQdnuzBdnaneYcgD4/90mDWjfb7J7eSNw6WfkFfhfqh4wAWyBPLv9RbnSdHZdHcrR+wL038x0cc=,iv:JBfuCPXcfsSJmyhsiOM9Q2Eg6EpMJ068sDtiNb/6e5Q=,tag:3aJaM1sav4InukV+xjPp6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
