---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-set
spec:
  chartRef:
    kind: OCIRepository
    name: arc-runner-set
  interval: 1h
  values:
    runnerScaleSetName: "k8s-runners"
    githubConfigUrl: "https://github.com/kcable194"
    githubConfigSecret: arc-github-pat
    controllerServiceAccount:
      namespace: actions-runner-system
      name: arc-gha-rs-controller
    minRunners: 0
    maxRunners: 2
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.322.0
            command: ["/home/runner/run.sh"]
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: 3000m
                memory: 6Gi
          - name: dind
            image: docker:dind
            args:
              - dockerd
              - --host=unix:///var/run/docker.sock
              - --insecure-registry=harbor-core.harbor.svc.cluster.local
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 2Gi
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
        volumes:
          - name: work
            emptyDir: {}
