---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
spec:
  dependsOn:
    - name: forgejo-postgres
      namespace: forgejo
  interval: 1h
  path: ./kubernetes/apps/forgejo/forgejo/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo
  wait: false
