---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./networkpolicies.yaml
  - ./forgejo-postgres/ks.yaml
  - ./forgejo/ks.yaml
