---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
spec:
  dependsOn:
    - name: forgejo
      namespace: forgejo
  interval: 1h
  path: ./kubernetes/apps/forgejo-runners/forgejo-runner/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo-runners
  wait: false
