---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    storageClass: longhorn
    size: 5Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-user
  backup:
    barmanObjectStore:
      destinationPath: s3://k8s-cnpg-backups/authentik-postgres/
      endpointURL: https://s3.us-east-005.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: authentik-postgres-b2
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: authentik-postgres-b2
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
