---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runners
components:
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./networkpolicies.yaml
  - ./arc-runner-set/ks.yaml
